# Generated by Django 3.1.3 on 2020-12-06 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
