# Generated by Django 3.1.3 on 2020-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('basketapp', '0002_remove_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
    ]
